FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
 && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY scheduler.py .

ENV PYTHONUNBUFFERED=1 \
    PG_HOST=db \
    PG_PORT=5432

CMD ["python", "scheduler.py"]
